[package]
name = "feather-shell"
version = "0.1.0"
authors = ["raad1masum <piraadwan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.3"
whoami = "0.8.1"